X201 CHK-5 : [MULTIPLE] - Basic server finished, Agent dev started.

diff --git a/agent/gnu+linux/SHELL/checkscripts/chkping b/agent/gnu+linux/SHELL/checkscripts/chkping
--- a/agent/gnu+linux/SHELL/checkscripts/chkping
+++ b/agent/gnu+linux/SHELL/checkscripts/chkping
@@ -3,7 +3,7 @@
 # Script      : chkping
 # Author(s)   : Pol Warnimont
 # Create date : 2015-04-27
-# Version     : 1.0 R1
+# Version     : 1.1 R1
 #
 # Description : A SRVMON check script - Check if gateway is reachable
 #
@@ -11,33 +11,65 @@
 # ---------
 #  2015-04-27 : Created script.
 #  2015-04-30 : Changed license to AGPLv3.
+#  2015-05-26 : Modifying script.
+#  2016-02-03 : Changed license.
 #
 # License
 # -------
-#  Copyright (C) 2015  Pol Warnimont
+#  Copyright (C) 2016  Pol Warnimont
 #
-#  This program is free software: you can redistribute it and/or modify
-#  it under the terms of the GNU Affero General Public License as
-#  published by the Free Software Foundation, either version 3 of the
-#  License, or (at your option) any later version.
+#  This program is free software; you can redistribute it and/or
+#  modify it under the terms of the GNU General Public License
+#  as published by the Free Software Foundation; either version 2
+#  of the License, or (at your option) any later version.
 #
 #  This program is distributed in the hope that it will be useful,
 #  but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU Affero General Public License for more details.
+#  GNU General Public License for more details.
 #
-#  You should have received a copy of the GNU Affero General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#  You should have received a copy of the GNU General Public License
+#  along with this program; if not, write to the Free Software
+#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
-ping -c4 192.168.1.1 > /dev/null 2>&1
+FAILCNT=0
+PINGCNT=0
 
-if [ $? -eq 0 ]
+if [ $# -eq 3 ]
 then
-  EXCODE=0
-  OUTPUT="Gateway is reachable"
-else
-  EXCODE=1
-  OUTPUT="Gateway unreachable"
-fi
+	while [ $PINGCNT -ne $2 ]
+	do
+		ping -c1 $1 > /dev/null 2>&1
+		
+		if [ $? -ne 0 ]
+		then
+			((FAILCNT = FAILCNT + 1))
+		fi
 
-echo "$EXCODE;$OUTPUT"
+		((PINGCNT = PINGCNT + 1))
+	done
+
+	if [ $FAILCNT -eq $2 ]
+	then
+		EXCODE=2
+		OUTPUT="$1 is unreachable!"
+	elif [ $FAILCNT -ge $3 ]
+	then
+		EXCODE=1
+		OUTPUT="$FAILCNT of $2 pings failed!"
+	else
+		EXCODE=0
+		OUTPUT="$1 is reachable!"
+	fi
+
+	echo "$EXCODE;$OUTPUT"
+	exit $EXCODE
+else
+	echo "Syntax error!"
+	echo "Usage: $0 <ip addr> <ping count> <warn count>"
+	echo "Ex.:   $0 192.168.1.1 4 2"
+	echo ""
+	echo "Copyright (C) 2016  Pol Warnimont"
+	echo "This script ($0) comes with ABSOLUTELY NO WARRANTY!"
+	exit 1
+fi
diff --git a/agent/gnu+linux/SHELL/checkscripts/chkproc b/agent/gnu+linux/SHELL/checkscripts/chkproc
--- a/agent/gnu+linux/SHELL/checkscripts/chkproc
+++ b/agent/gnu+linux/SHELL/checkscripts/chkproc
@@ -11,37 +11,51 @@
 # ---------
 #  2015-04-27 : Created script.
 #  2015-04-30 : Changed license to AGPLv3.
+#  2015-05-26 : Modified script.
+#  2016-02-03 : Changed license.
 #
 # License
 # -------
-#  Copyright (C) 2015  Pol Warnimont
+#  Copyright (C) 2016  Pol Warnimont
 #
-#  This program is free software: you can redistribute it and/or modify
-#  it under the terms of the GNU Affero General Public License as
-#  published by the Free Software Foundation, either version 3 of the
-#  License, or (at your option) any later version.
+#  This program is free software; you can redistribute it and/or
+#  modify it under the terms of the GNU General Public License
+#  as published by the Free Software Foundation; either version 2
+#  of the License, or (at your option) any later version.
 #
 #  This program is distributed in the hope that it will be useful,
 #  but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU Affero General Public License for more details.
+#  GNU General Public License for more details.
 #
-#  You should have received a copy of the GNU Affero General Public License
-#  along with this program.  If not, see <http://www.gnu.org/licenses/>. 
+#  You should have received a copy of the GNU General Public License
+#  along with this program; if not, write to the Free Software
+#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
-PROCCOUNT=`ps aux | wc -l`
+if [ $# -eq 2 ]
+then
+	PROCCOUNT=`ps aux | wc -l`
 
-if [ $PROCCOUNT -gt 200 ]
-then
-  EXCODE=2
-  OUTPUT="$PROCCOUNT running processes (>200)!"
-elif [ $PROCCOUNT -gt 150 ]
-then
-  EXCODE=1
-  OUTPUT="$PROCCOUNT running processes (>150)!"
+	if [ $PROCCOUNT -ge $2 ]
+	then
+		OUTPUT="$PROCCOUNT running processes (>$2)!"
+		EXCODE=2
+	elif [ $PROCCOUNT -ge $1 ]
+	then
+		OUTPUT="$PROCCOUNT running processes (>$1)!"
+		EXCODE=1
+	else
+		OUTPUT="Process count Ok ($PROCCOUNT)."
+		EXCODE=0
+	fi
+
+	echo "$EXCODE;$OUTPUT;$PROCCOUNT;$1;$2"
+	exit $EXCODE
 else
-  EXCODE=0
-  OUTPUT="Process count Ok ($PROCCOUNT)."
+	echo "Syntax error!"
+	echo "Usage: $0 <warning count> <critical count>"
+	echo "Ex.:   $0 200 300"
+	echo ""
+	echo "Copyright (C) 2016  Pol Warnimont"
+	echo "This script ($0) comes with ABSOLUTELY NO WARRANTY!"
 fi
-
-echo "$EXCODE;$OUTPUT"
